/**
 * Shared GitHub PR creation helper.
 *
 * Keeps command construction, title sanitization, duplicate PR lookup, body-file
 * handling, and URL extraction in one place for all agents.
 */

function cleanCommandOutput(output) {
    if (!output) return '';
    return output.split('\n').filter(function(line) {
        return line.indexOf('Script started') === -1 &&
               line.indexOf('Script done') === -1 &&
               line.indexOf('COMMAND=') === -1 &&
               line.indexOf('COMMAND_EXIT_CODE=') === -1;
    }).join('\n').trim();
}

function sanitizeTitle(title) {
    return String(title || '')
        .replace(/\r?\n/g, ' ')
        .replace(/"/g, '\\"')
        .replace(/->/g, '→')
        .replace(/<-/g, '←')
        .replace(/[<>`|&;$]/g, ' ')
        .replace(/\s{2,}/g, ' ')
        .trim();
}

/** Escape a string so it can safely be placed inside a double-quoted shell argument.
 *  CliCommandExecutor rejects: ; \n \r ` $(...) ${...} && || | > <
 *  Jira summaries often contain angle brackets, arrows, etc. */
function sanitizeCommitMessage(message) {
    return String(message || '')
        .replace(/->/g, '→')
        .replace(/<-/g, '←')
        .replace(/"/g, '\\"')
        .replace(/[<>\`\|&;$\r\n]/g, ' ')
        .replace(/\s{2,}/g, ' ')
        .trim();
}

function extractPrUrl(output, runCommand, branchName, workingDir) {
    var cleaned = cleanCommandOutput(output);
    var urlMatch = cleaned.match(/https:\/\/(?:github\.com|[^/\s]*gitlab[^/\s]*|gitlab\.example\.com)\/[^\s]+/);
    if (urlMatch) return urlMatch[0];

    var prNumberMatch = cleaned.match(/#(\d+)/);
    if (prNumberMatch) {
        try {
            var remoteUrl = cleanCommandOutput(runCommand('git config --get remote.origin.url', workingDir) || '');
            var repoMatch = remoteUrl.match(/github\.com[:/]([^/?#\s]+\/[^/?#\s]+)/);
            if (repoMatch) {
                return 'https://github.com/' + repoMatch[1].replace(/\.git$/, '') + '/pull/' + prNumberMatch[1];
            }
        } catch (e) {}
    }

    try {
        var listOutput = cleanCommandOutput(
            runCommand('gh pr list --head ' + branchName + ' --json url --jq ".[0].url"', workingDir) || ''
        );
        if (listOutput && listOutput.startsWith('https://')) return listOutput;
    } catch (e) {}

    return null;
}

function defaultRunCommand(command, workingDir) {
    var args = { command: command };
    if (workingDir) args.workingDirectory = workingDir;
    return cli_execute_command(args);
}

function defaultReadFile(path) {
    try {
        var content = file_read({ path: path });
        return (content && content.trim()) ? content : null;
    } catch (e) {
        return null;
    }
}

// GitHub limits PR bodies to 65536 characters. Keep a safety margin so
// gh pr create does not fail on oversized bodies generated by agents.
var MAX_GH_PR_BODY_LENGTH = 60000;

function isSafeRefName(ref) {
    return ref &&
        typeof ref === 'string' &&
        ref[0] !== '-' &&
        ref.indexOf('..') === -1 &&
        /^[A-Za-z0-9._/-]+$/.test(ref);
}

function lastNonEmptyLine(output) {
    var lines = cleanCommandOutput(output || '')
        .split(/\r?\n/)
        .map(function(line) { return line.trim(); })
        .filter(function(line) { return line; });
    return lines[lines.length - 1] || '';
}

function branchContainsBase(runCommand, workingDir, baseBranch) {
    if (!isSafeRefName(baseBranch)) {
        throw new Error('Unsafe base branch name: ' + baseBranch);
    }

    var baseRef = 'origin/' + baseBranch;
    var baseSha = lastNonEmptyLine(runCommand('git rev-parse ' + baseRef, workingDir));
    if (!baseSha) {
        throw new Error('Could not resolve ' + baseRef);
    }

    try {
        var mergeBase = lastNonEmptyLine(runCommand('git merge-base ' + baseRef + ' HEAD', workingDir));
        return mergeBase === baseSha;
    } catch (e) {
        return false;
    }
}

function branchHasMergeBase(runCommand, workingDir, baseBranch) {
    if (!isSafeRefName(baseBranch)) {
        throw new Error('Unsafe base branch name: ' + baseBranch);
    }

    try {
        var mergeBase = lastNonEmptyLine(
            runCommand('git merge-base origin/' + baseBranch + ' HEAD', workingDir)
        );
        return !!mergeBase;
    } catch (e) {
        return false;
    }
}

function fetchAdditionalHistoryForMergeBase(runCommand, workingDir, baseBranch, branchName) {
    var refSpecs = [
        '+refs/heads/' + baseBranch + ':refs/remotes/origin/' + baseBranch
    ];
    if (branchName && isSafeRefName(branchName)) {
        refSpecs.push('+refs/heads/' + branchName + ':refs/remotes/origin/' + branchName);
    }

    var deepenCommands = [];
    for (var i = 0; i < refSpecs.length; i++) {
        deepenCommands.push('git -c fetch.recurseSubmodules=no fetch --deepen=100 origin ' + refSpecs[i]);
    }
    deepenCommands.push('git -c fetch.recurseSubmodules=no fetch --unshallow origin');

    for (var j = 0; j < deepenCommands.length; j++) {
        try {
            runCommand(deepenCommands[j], workingDir);
        } catch (e) {
            console.warn('Could not deepen git history for merge-base lookup:', e.message || e);
        }
        if (branchHasMergeBase(runCommand, workingDir, baseBranch)) {
            return true;
        }
    }
    return false;
}

function buildOriginFetchCommand(refSpec) {
    return 'git -c fetch.recurseSubmodules=no fetch origin' + (refSpec ? ' ' + refSpec : '');
}

/**
 * Ensures `refs/remotes/origin/<branchName>` exists and is up to date.
 *
 * `git fetch origin <branchName>` (no destination refspec) only updates
 * FETCH_HEAD — it never creates/updates the `origin/<branchName>` tracking
 * ref. That "worked" for base branch "main" only because long-lived cached
 * checkouts (e.g. CI dependency caches) already had `origin/main` from an
 * earlier full clone or wildcard fetch. Any other base branch (e.g. a
 * fixVersion-derived "develop/3.9.0") that was never explicitly fetched with
 * a destination refspec into that cache genuinely has no local tracking ref,
 * so every later git command that reads `origin/<branchName>` (merge-base,
 * merge, diff) fails with "unknown revision or path not in the working
 * tree" — even though the branch exists on the remote.
 *
 * Uses an explicit refspec (`+refs/heads/<b>:refs/remotes/origin/<b>`) so the
 * tracking ref is created/updated regardless of the remote's configured
 * fetch refspec (e.g. a shallow/single-branch clone in CI).
 *
 * @returns {boolean} true if the fetch succeeded (ref should now exist)
 */
function ensureRemoteBranchRef(runCommand, workingDir, branchName) {
    if (!branchName || !isSafeRefName(branchName)) return false;

    try {
        runCommand(
            'git -c fetch.recurseSubmodules=no fetch origin +refs/heads/' + branchName + ':refs/remotes/origin/' + branchName,
            workingDir
        );
        return true;
    } catch (e) {
        console.warn('Could not fetch explicit ref for origin/' + branchName + ':', e.message || e);
        return false;
    }
}

function readTrackedStatus(runCommand, workingDir) {
    return cleanCommandOutput(
        runCommand('git status --porcelain --ignore-submodules=dirty', workingDir) || ''
    );
}

function readStagedDiffStat(runCommand, workingDir) {
    return cleanCommandOutput(
        runCommand('git diff --cached --stat', workingDir) || ''
    );
}

function isSubmodulePath(runCommand, workingDir, path) {
    try {
        var stageOutput = cleanCommandOutput(
            runCommand('git ls-files --stage -- "' + path + '"', workingDir) || ''
        );
        return stageOutput.split('\n').some(function(line) {
            return line.trim().indexOf('160000 ') !== -1;
        });
    } catch (e) {
        return false;
    }
}

function resolveMergeConflicts(runCommand, workingDir, baseBranch, branchName) {
    var conflictFiles = [];
    try {
        var statusRaw = cleanCommandOutput(runCommand('git status --short', workingDir) || '');
        conflictFiles = statusRaw.split('\n')
            .filter(function(line) { return /^(UU|AA|DD|AU|UA|DU|UD) /.test(line.trim()); })
            .map(function(line) { return line.trim().substring(3).trim(); })
            .filter(Boolean);
    } catch (statusError) {
        return { resolved: false, error: 'Could not read conflict status' };
    }

    if (conflictFiles.length === 0) {
        return { resolved: false, error: 'No conflicted files detected' };
    }

    var mergeBase = '';
    try {
        mergeBase = lastNonEmptyLine(runCommand('git merge-base origin/' + baseBranch + ' HEAD', workingDir));
    } catch (e) {
        console.warn('Could not determine merge base for conflict resolution:', e.message || e);
    }

    conflictFiles.forEach(function(file) {
        try {
            if (isSubmodulePath(runCommand, workingDir, file)) {
                console.log('  Submodule conflict — adopting origin/' + baseBranch + ' version for', file);
                runCommand('git checkout --theirs -- "' + file + '"', workingDir);
                runCommand('git add -- "' + file + '"', workingDir);
                return;
            }

            var branchChanged = false;
            if (mergeBase) {
                try {
                    var diff = cleanCommandOutput(runCommand('git diff ' + mergeBase + ' HEAD -- "' + file + '"', workingDir) || '');
                    branchChanged = !!diff.trim();
                } catch (diffError) {
                    console.warn('Could not determine change side for', file, ':', diffError.message || diffError);
                }
            }

            if (branchChanged) {
                console.log('  Keeping branch version for', file);
                runCommand('git checkout --ours -- "' + file + '"', workingDir);
            } else {
                console.log('  Keeping origin/' + baseBranch + ' version for', file);
                runCommand('git checkout --theirs -- "' + file + '"', workingDir);
            }
            runCommand('git add -- "' + file + '"', workingDir);
        } catch (resolveError) {
            console.warn('Could not auto-resolve', file, ':', resolveError.message || resolveError);
        }
    });

    var stillUnmerged = cleanCommandOutput(
        runCommand('git diff --name-only --diff-filter=U', workingDir) || ''
    ).split('\n').map(function(s) { return s.trim(); }).filter(Boolean);

    if (stillUnmerged.length > 0) {
        return { resolved: false, conflictFiles: stillUnmerged, error: 'Unresolved conflicts remain: ' + stillUnmerged.join(', ') };
    }

    try {
        runCommand('git commit -m "Merge origin/' + baseBranch + ' into ' + branchName + '"', workingDir);
        console.log('✅ Auto-resolved merge conflicts and committed sync of origin/' + baseBranch);
        return { resolved: true };
    } catch (commitError) {
        return { resolved: false, error: 'Conflict files resolved but merge commit failed: ' + (commitError.message || commitError) };
    }
}

function syncBranchWithBase(options) {
    options = options || {};
    var branchName = options.branchName;
    var baseBranch = options.baseBranch || 'main';
    var workingDir = options.workingDir || null;
    var runCommand = options.runCommand || defaultRunCommand;

    if (!branchName) return { success: false, error: 'branchName is required' };
    if (!isSafeRefName(branchName)) return { success: false, error: 'Unsafe branch name: ' + branchName };
    if (!isSafeRefName(baseBranch)) return { success: false, error: 'Unsafe base branch name: ' + baseBranch };

    try {
        console.log('Synchronizing ' + branchName + ' with origin/' + baseBranch + ' before publishing...');
        ensureRemoteBranchRef(runCommand, workingDir, baseBranch);

        var upToDate = branchContainsBase(runCommand, workingDir, baseBranch);
        if (upToDate) {
            console.log('✅ Branch already contains origin/' + baseBranch);
            return { success: true, updated: false };
        }

        if (!branchHasMergeBase(runCommand, workingDir, baseBranch) &&
                !fetchAdditionalHistoryForMergeBase(runCommand, workingDir, baseBranch, branchName)) {
            return {
                success: false,
                unrecoverableByAgent: true,
                error: 'No merge base found between HEAD and origin/' + baseBranch + '; refusing to merge unrelated histories. Fetch full branch history or recreate the branch from origin/' + baseBranch + ' before publishing.'
            };
        }

        var status = readTrackedStatus(runCommand, workingDir);
        if (status.trim()) {
            try {
                runCommand('git submodule update --init --recursive', workingDir);
                status = readTrackedStatus(runCommand, workingDir);
            } catch (submoduleError) {
                console.warn('Could not realign submodules before syncing with base:', submoduleError.message || submoduleError);
            }
        }
        if (status.trim()) {
            return {
                success: false,
                error: 'Cannot sync with origin/' + baseBranch + ' because the working tree is not clean:\n' + status
            };
        }

        runCommand('git merge --no-edit origin/' + baseBranch, workingDir);
        console.log('✅ Merged origin/' + baseBranch + ' into ' + branchName);
        return { success: true, updated: true };
    } catch (error) {
        var autoResolve = resolveMergeConflicts(runCommand, workingDir, baseBranch, branchName);
        if (autoResolve.resolved) {
            return { success: true, updated: true, autoResolved: true };
        }

        var conflictFiles = autoResolve.conflictFiles || [];
        try { runCommand('git merge --abort', workingDir); } catch (abortError) {}

        var message = error && error.message ? error.message : String(error);
        if (conflictFiles.length > 0) {
            message = 'Merge conflict while syncing with origin/' + baseBranch + ': ' + conflictFiles.join(', ');
        } else if (autoResolve.error && autoResolve.error !== 'No conflicted files detected') {
            // A specific auto-resolve failure (unresolved conflicts, commit failure)
            // is more actionable than the original git error — surface it.
            message = autoResolve.error;
        }
        // Otherwise autoResolve found zero conflict markers, meaning `error` was
        // never a real merge conflict (e.g. a missing origin/<baseBranch> ref) —
        // keep the original git error instead of the misleading generic message.
        console.warn('Could not synchronize branch with base:', message);
        return {
            success: false,
            conflict: conflictFiles.length > 0,
            conflictFiles: conflictFiles,
            error: message
        };
    }
}

function resolveBodyContent(options) {
    if (options.bodyContent) return options.bodyContent;

    var readFile = options.readFile || defaultReadFile;
    var candidates = options.bodyFileCandidates || ['outputs/response.md'];
    for (var i = 0; i < candidates.length; i++) {
        var content = readFile(candidates[i]);
        if (content) return content;
    }

    return options.defaultBody || 'Automated changes.';
}

function createPullRequest(options) {
    options = options || {};
    var branchName = options.branchName;
    var baseBranch = options.baseBranch || 'main';
    var workingDir = options.workingDir || null;
    var runCommand = options.runCommand || defaultRunCommand;
    var scm = options.scm || null;

    if (!branchName) return { success: false, error: 'branchName is required' };

    if (scm && typeof scm.createPr === 'function') {
        var body = resolveBodyContent(options);
        try {
            var created = scm.createPr({
                title: sanitizeTitle(options.title),
                branchName: branchName,
                baseBranch: baseBranch,
                body: body,
                removeSourceBranch: options.removeSourceBranch
            });
            if (created && created.success) {
                console.log('✅ Pull/Merge Request created:', created.prUrl || '(URL not found)');
                return created;
            }
            return created || { success: false, error: 'SCM provider returned no result from createPr' };
        } catch (error) {
            var errMsg = error && error.toString ? error.toString() : String(error);
            if (errMsg.indexOf('already exists') !== -1 || errMsg.indexOf('Another open merge request') !== -1) {
                console.warn('SCM provider reported an existing PR/MR for branch ' + branchName + ': ' + errMsg);
            }
            return { success: false, error: errMsg };
        }
    }

    try {
        var existingPr = cleanCommandOutput(
            runCommand('gh pr list --head ' + branchName + ' --json url --jq ".[0].url"', workingDir) || ''
        );
        if (existingPr && existingPr.startsWith('https://')) {
            console.log('✅ PR already exists for branch ' + branchName + ': ' + existingPr);
            return { success: true, prUrl: existingPr, alreadyExisted: true };
        }
    } catch (e) {
        console.warn('Could not check for existing PR (non-fatal):', e);
    }

    // file_write()/file_read() (dmtools' MCP file tools) are sandboxed to the
    // JSRunner's own cwd (this repo's .dmtools/ dir — where config.js was
    // discovered) and cannot reach files outside it under any path form,
    // confirmed by probing a guaranteed-existing repo-root file. Meanwhile
    // cli_execute_command (the shell gh/git/find/etc run through) resolves
    // against the repo root that actions/checkout populated, and the CLI
    // agent's own Write tool also lands files in that repo root — so an
    // output file can be readable via file_read (if written to .dmtools/,
    // found as a plain relative candidate) or only via cli_execute_command
    // cat (if written to repo root, found as an absolute candidate) —
    // outputFiles.js's readOutputFileDetailed() tries both and reports back
    // which literal path actually worked. Reuse that exact path for --body-file:
    // a relative .dmtools/-rooted path resolves fine for cli_execute_command
    // too (it just walks down from repo root through .dmtools/), and an
    // absolute path is unambiguous either way — no more guessing a prefix.
    var readFileDetailed = options.readFileDetailed || null;
    var bodyFileCandidates = options.bodyFileCandidates || ['outputs/response.md'];
    var resolvedBodyFilePath = null;
    var bodyContent = options.bodyContent || null;

    if (!bodyContent && readFileDetailed) {
        for (var ci = 0; ci < bodyFileCandidates.length; ci++) {
            var detailed = readFileDetailed(bodyFileCandidates[ci]);
            if (detailed && detailed.content) {
                bodyContent = detailed.content;
                resolvedBodyFilePath = detailed.path;
                break;
            }
        }
    }
    if (!bodyContent) {
        bodyContent = resolveBodyContent(options);
    }

    if (bodyContent && bodyContent.length > MAX_GH_PR_BODY_LENGTH) {
        console.warn('PR body exceeds ' + MAX_GH_PR_BODY_LENGTH + ' characters (' + bodyContent.length + '); truncating to fit GitHub limit.');
        var truncationNotice = '\n\n_…PR body truncated by automation; original full content was ' + bodyContent.length + ' characters._';
        bodyContent = bodyContent.substring(0, MAX_GH_PR_BODY_LENGTH - truncationNotice.length) + truncationNotice;
        // The file on disk still has the untruncated content — fall back to
        // --body with the truncated string rather than --body-file.
        resolvedBodyFilePath = null;
    }

    var command;
    if (resolvedBodyFilePath) {
        command = 'gh pr create --title "' + sanitizeTitle(options.title) + '"' +
            ' --body-file "' + resolvedBodyFilePath + '"' +
            ' --base ' + baseBranch +
            ' --head ' + branchName;
    } else {
        command = 'gh pr create --title "' + sanitizeTitle(options.title) + '"' +
            ' --body "' + sanitizeCommitMessage(bodyContent) + '"' +
            ' --base ' + baseBranch +
            ' --head ' + branchName;
    }

    try {
        var output = runCommand(command, workingDir) || '';
        var prUrl = extractPrUrl(output, runCommand, branchName, workingDir);
        console.log('✅ Pull Request created:', prUrl || '(URL not found)');
        return { success: true, prUrl: prUrl, output: output };
    } catch (error) {
        var errMsg = error.toString();
        if (errMsg.indexOf('already exists') !== -1 || errMsg.indexOf('pull request for branch') !== -1) {
            var existingUrl = extractPrUrl('', runCommand, branchName, workingDir);
            if (existingUrl) {
                console.log('✅ Found existing PR:', existingUrl);
                return { success: true, prUrl: existingUrl, alreadyExisted: true };
            }
        }
        console.error('Failed to create Pull Request:', errMsg);
        return { success: false, error: errMsg };
    }
}

module.exports = {
    cleanCommandOutput: cleanCommandOutput,
    sanitizeTitle: sanitizeTitle,
    sanitizeCommitMessage: sanitizeCommitMessage,
    buildOriginFetchCommand: buildOriginFetchCommand,
    ensureRemoteBranchRef: ensureRemoteBranchRef,
    readTrackedStatus: readTrackedStatus,
    readStagedDiffStat: readStagedDiffStat,
    syncBranchWithBase: syncBranchWithBase,
    createPullRequest: createPullRequest
};
